### 中級（実務応用：pandas & 可視化）

Series を {'a':1,'b':2,'c':3} から作成し index 指定。

In [17]:
import pandas as pd
import numpy as np

In [ ]:
d={'a':1,'b':2,'c':3}
#シリーズを作成
pd_series=pd.Series(d)
#インデックスから値を取得
print(pd_series['c'])
#DFを作るときはリストから作成。辞書型からは作れない
df=pd.DataFrame([d])
df

3

   a  b  c
0  1  2  3

In [ ]:
#乱数で行列作成
A=np.array([[np.random.randint(0,10) for _ in range(10)] for _ in range(3)]).reshape(10,3)
#DFに変換、カラム名をｘ，ｙ，ｚに
df=pd.DataFrame(A,columns=['x','y','z'])
df

In [ ]:
url = 'https://www.exoplanetkyoto.org/exohtml/JA_All_Exoplanets.html'
exoplanets = pd.DataFrame(pd.read_html(url, header=0)[0])

In [ ]:
exoplanets.info()

In [51]:
exoplanets['公転周期 (年)']=exoplanets['公転周期 (年)'].astype('int32')

In [ ]:
exoplanets.info()

In [59]:
exoplanets_opt=exoplanets.set_index('系外惑星名')

In [60]:
exoplanets_opt

,No,別名,半径 (木星半径),質量 (木星質量),軌道長半径 (天文単位),離心率,公転周期 (年),公転周期 (日),想像図
系外惑星名,,,,,,,,,
CWISE J101533.05-111501.0 (AB)b,1,CWISE J101523.92-111539.6,0.9078,60.0000,5800.0000,0.000,7063,2.580000e+06,NaN
Gaia EDR3 2077240046296834304 b,2,NaN,0.8100,0.4549,0.0320,0.000,0,4.996700e+00,NaN
"""PSR J0636+5129\tb""",3,PSR J0636+5128 b,0.9078,8.0000,0.0036,0.000,0,6.700000e-02,NaN
AB Aur b,4,NaN,0.9078,9.0000,93.9000,0.400,0,0.000000e+00,NaN
AB Dor C b,5,NaN,0.9078,13.0000,0.5800,0.000,0,0.000000e+00,NaN
...,...,...,...,...,...,...,...,...,...
91 Aqr b,6665,NaN,1.0499,3.2000,0.7000,0.027,0,1.814000e+02,NaN
94 Cet Ab,6666,"""HD 19994 Ab, GJ 128 Ab, HR 962 Ab""",0.9078,1.3700,1.3050,0.063,1,4.662000e+02,NaN
109 Psc b,6667,HD 10697 b,1.1520,5.7430,2.0510,0.104,2,1.075400e+03,NaN
112 Psc b,6668,HD 12235 b,0.1987,0.0330,0.0540,0.376,0,4.400000e+00,NaN
112 Psc c,6669,HD 12235 c,0.9078,9.8660,22.2100,0.174,99,3.633670e+04,NaN

In [61]:
exoplanets_opt.reset_index(drop=True)

,No,別名,半径 (木星半径),質量 (木星質量),軌道長半径 (天文単位),離心率,公転周期 (年),公転周期 (日),想像図
0,1,CWISE J101523.92-111539.6,0.9078,60.0000,5800.0000,0.000,7063,2.580000e+06,NaN
1,2,NaN,0.8100,0.4549,0.0320,0.000,0,4.996700e+00,NaN
2,3,PSR J0636+5128 b,0.9078,8.0000,0.0036,0.000,0,6.700000e-02,NaN
3,4,NaN,0.9078,9.0000,93.9000,0.400,0,0.000000e+00,NaN
4,5,NaN,0.9078,13.0000,0.5800,0.000,0,0.000000e+00,NaN
...,...,...,...,...,...,...,...,...,...
6664,6665,NaN,1.0499,3.2000,0.7000,0.027,0,1.814000e+02,NaN
6665,6666,"""HD 19994 Ab, GJ 128 Ab, HR 962 Ab""",0.9078,1.3700,1.3050,0.063,1,4.662000e+02,NaN
6666,6667,HD 10697 b,1.1520,5.7430,2.0510,0.104,2,1.075400e+03,NaN
6667,6668,HD 12235 b,0.1987,0.0330,0.0540,0.376,0,4.400000e+00,NaN
6668,6669,HD 12235 c,0.9078,9.8660,22.2100,0.174,99,3.633670e+04,NaN

In [62]:
exoplanets.insert(0,'ones',1)
exoplanets

,ones,No,系外惑星名,別名,半径 (木星半径),質量 (木星質量),軌道長半径 (天文単位),離心率,公転周期 (年),公転周期 (日),想像図
0,1,1,CWISE J101533.05-111501.0 (AB)b,CWISE J101523.92-111539.6,0.9078,60.0000,5800.0000,0.000,7063,2.580000e+06,NaN
1,1,2,Gaia EDR3 2077240046296834304 b,NaN,0.8100,0.4549,0.0320,0.000,0,4.996700e+00,NaN
2,1,3,"""PSR J0636+5129\tb""",PSR J0636+5128 b,0.9078,8.0000,0.0036,0.000,0,6.700000e-02,NaN
3,1,4,AB Aur b,NaN,0.9078,9.0000,93.9000,0.400,0,0.000000e+00,NaN
4,1,5,AB Dor C b,NaN,0.9078,13.0000,0.5800,0.000,0,0.000000e+00,NaN
...,...,...,...,...,...,...,...,...,...,...,...
6664,1,6665,91 Aqr b,NaN,1.0499,3.2000,0.7000,0.027,0,1.814000e+02,NaN
6665,1,6666,94 Cet Ab,"""HD 19994 Ab, GJ 128 Ab, HR 962 Ab""",0.9078,1.3700,1.3050,0.063,1,4.662000e+02,NaN
6666,1,6667,109 Psc b,HD 10697 b,1.1520,5.7430,2.0510,0.104,2,1.075400e+03,NaN
6667,1,6668,112 Psc b,HD 12235 b,0.1987,0.0330,0.0540,0.376,0,4.400000e+00,NaN
6668,1,6669,112 Psc c,HD 12235 c,0.9078,9.8660,22.2100,0.174,99,3.633670e+04,NaN

In [ ]:
exoplanets.describe()

In [ ]:
exoplanets.describe().T

In [66]:
exoplanets.loc[exoplanets['系外惑星名']=='AB Aur b']

,ones,No,系外惑星名,別名,半径 (木星半径),質量 (木星質量),軌道長半径 (天文単位),離心率,公転周期 (年),公転周期 (日),想像図
3,1,4,AB Aur b,NaN,0.9078,9.0,93.9,0.4,0,0.0,NaN

In [69]:
exoplanets.iloc[2,1]

np.int64(3)

In [71]:
exoplanets[exoplanets['質量 (木星質量)']>=100]

,ones,No,系外惑星名,別名,半径 (木星半径),質量 (木星質量),軌道長半径 (天文単位),離心率,公転周期 (年),公転周期 (日),想像図
380,1,381,HAT-P-2 c,NaN,0.9078,104.0,4.00,0.000,0,0.00,NaN
1030,1,1031,HD 130322 b,NaN,1.0499,136.0,0.09,0.044,0,10.72,NaN